services:
  nextjs:
    build:
      context: .
      args:
        NEXT_PUBLIC_APP_ENV: ${NEXT_PUBLIC_APP_ENV}
        NEXT_PUBLIC_PAGE_SIZE: ${NEXT_PUBLIC_PAGE_SIZE}
        NEXT_PUBLIC_BASE_URL: ${NEXT_PUBLIC_BASE_URL}
        NEXT_PUBLIC_GOOGLE_MAPS_API_KEY: ${NEXT_PUBLIC_GOOGLE_MAPS_API_KEY}
        NEXT_PUBLIC_GOOGLE_PLACE_API_KEY: ${NEXT_PUBLIC_GOOGLE_PLACE_API_KEY}
        NEXT_PUBLIC_TOKEN: ${NEXT_PUBLIC_TOKEN}
        NEXT_PUBLIC_PAGE_SIZES: ${NEXT_PUBLIC_PAGE_SIZES}
        NEXT_PUBLIC_BASE_PATH: ${NEXT_PUBLIC_BASE_PATH}
    image: logistic-portal:latest
    restart: always
