export const mockVehicles = [
    {
        id: "TRK-001",
        type: "truck",
        make: "Freightliner",
        model: "Cascadia",
        year: 2022,
        vin: "1FUJGHDV8NLAA1234",
        licensePlate: "TRK-001-NY",
        status: "active",
        driver: "John Smith",
        driverId: "DRV-001",
        location: "New York, NY",
        coordinates: [-74.006, 40.7128],
        mileage: 45892,
        fuelLevel: 85,
        lastMaintenance: "2024-01-15",
        nextMaintenance: "2024-04-15",
        maintenanceDue: false,
        insuranceExpiry: "2024-12-31",
        registrationExpiry: "2024-11-30",
        capacity: "26,000 lbs",
        currentLoad: "18,500 lbs",
        utilization: 71,
        alerts: [],
        documents: ["Registration", "Insurance", "Inspection"],
        notes: "Regular maintenance completed. Good condition.",
    },
    {
        id: "TRK-002",
        type: "truck",
        make: "Kenworth",
        model: "T680",
        year: 2021,
        vin: "1XKYDP9X5MJ123456",
        licensePlate: "TRK-002-IL",
        status: "maintenance",
        driver: "Sarah Johnson",
        driverId: "DRV-002",
        location: "Chicago, IL",
        coordinates: [-87.6298, 41.8781],
        mileage: 78541,
        fuelLevel: 42,
        lastMaintenance: "2024-01-20",
        nextMaintenance: "2024-04-20",
        maintenanceDue: true,
        insuranceExpiry: "2024-12-31",
        registrationExpiry: "2024-10-15",
        capacity: "26,000 lbs",
        currentLoad: "0 lbs",
        utilization: 0,
        alerts: ["Maintenance Due", "Low Fuel"],
        documents: ["Registration", "Insurance"],
        notes: "Scheduled for brake inspection and oil change.",
    },
    {
        id: "VAN-001",
        type: "van",
        make: "Mercedes-Benz",
        model: "Sprinter",
        year: 2023,
        vin: "WD3PE8CC5NP123456",
        licensePlate: "VAN-001-CA",
        status: "active",
        driver: "Michael Brown",
        driverId: "DRV-003",
        location: "Los Angeles, CA",
        coordinates: [-118.2437, 34.0522],
        mileage: 32145,
        fuelLevel: 72,
        lastMaintenance: "2024-01-10",
        nextMaintenance: "2024-04-10",
        maintenanceDue: false,
        insuranceExpiry: "2024-12-31",
        registrationExpiry: "2024-09-30",
        capacity: "3,500 lbs",
        currentLoad: "2,100 lbs",
        utilization: 60,
        alerts: [],
        documents: ["Registration", "Insurance", "Inspection"],
        notes: "Excellent condition. Recently serviced.",
    },
    {
        id: "CAR-001",
        type: "car",
        make: "Toyota",
        model: "Camry",
        year: 2022,
        vin: "4T1C11AK5NU123456",
        licensePlate: "CAR-001-TX",
        status: "available",
        driver: "Unassigned",
        driverId: null,
        location: "Houston, TX",
        coordinates: [-95.3698, 29.7604],
        mileage: 12567,
        fuelLevel: 90,
        lastMaintenance: "2024-01-05",
        nextMaintenance: "2024-04-05",
        maintenanceDue: false,
        insuranceExpiry: "2024-12-31",
        registrationExpiry: "2024-08-15",
        capacity: "500 lbs",
        currentLoad: "0 lbs",
        utilization: 0,
        alerts: [],
        documents: ["Registration", "Insurance", "Inspection"],
        notes: "Available for assignment. Good fuel economy.",
    },
    {
        id: "TRK-003",
        type: "truck",
        make: "Volvo",
        model: "VNL",
        year: 2020,
        vin: "4V4NC9EH5LN123456",
        licensePlate: "TRK-003-FL",
        status: "active",
        driver: "David Wilson",
        driverId: "DRV-004",
        location: "Miami, FL",
        coordinates: [-80.1918, 25.7617],
        mileage: 56789,
        fuelLevel: 65,
        lastMaintenance: "2024-01-25",
        nextMaintenance: "2024-04-25",
        maintenanceDue: false,
        insuranceExpiry: "2024-12-31",
        registrationExpiry: "2024-07-20",
        capacity: "26,000 lbs",
        currentLoad: "22,000 lbs",
        utilization: 85,
        alerts: ["High Utilization"],
        documents: ["Registration", "Insurance", "Inspection"],
        notes: "High-performing vehicle. Regular long-haul routes.",
    },
    {
        id: "FRK-001",
        type: "forklift",
        make: "Toyota",
        model: "8FGU25",
        year: 2019,
        vin: "TY8FGU25123456789",
        licensePlate: "FRK-001-IL",
        status: "outOfService",
        driver: "Unassigned",
        driverId: null,
        location: "Chicago, IL",
        coordinates: [-87.6298, 41.8781],
        mileage: 8765,
        fuelLevel: 20,
        lastMaintenance: "2024-01-02",
        nextMaintenance: "2024-04-02",
        maintenanceDue: true,
        insuranceExpiry: "2024-12-31",
        registrationExpiry: "2024-06-30",
        capacity: "5,000 lbs",
        currentLoad: "0 lbs",
        utilization: 0,
        alerts: ["Out of Service", "Maintenance Due", "Low Fuel"],
        documents: ["Registration", "Insurance"],
        notes: "Hydraulic system repair needed. Parts on order.",
    },
    {
        id: "VAN-002",
        type: "van",
        make: "Ford",
        model: "Transit",
        year: 2021,
        vin: "1FTBW2CM5MKA12345",
        licensePlate: "VAN-002-WA",
        status: "active",
        driver: "Emily Davis",
        driverId: "DRV-005",
        location: "Seattle, WA",
        coordinates: [-122.3321, 47.6062],
        mileage: 28976,
        fuelLevel: 78,
        lastMaintenance: "2024-01-12",
        nextMaintenance: "2024-04-12",
        maintenanceDue: false,
        insuranceExpiry: "2024-12-31",
        registrationExpiry: "2024-05-15",
        capacity: "4,650 lbs",
        currentLoad: "3,200 lbs",
        utilization: 69,
        alerts: [],
        documents: ["Registration", "Insurance", "Inspection"],
        notes: "Reliable vehicle for urban deliveries.",
    },
];